/**
 * Phase 1.1: Recurring Transactions Auto-Entry
 * Checks on app load if any recurring transactions need to be created today.
 * Uses localStorage to track last-run date and avoid duplicates.
 */

import { db, Transaction, generateUUID, syncAccountToAsset } from '@/db/schema'

const LAST_RUN_KEY = 'pennyflow-recurring-last-run'

export interface PendingRecurring {
  transaction: Transaction
  shouldCreate: boolean
}

export class RecurringTransactionService {
  /**
   * Check if recurring processor has already run today
   */
  static hasRunToday(): boolean {
    if (typeof window === 'undefined') return true
    const lastRun = localStorage.getItem(LAST_RUN_KEY)
    const today = new Date().toISOString().split('T')[0]
    return lastRun === today
  }

  /**
   * Mark today as processed
   */
  static markAsRun(): void {
    if (typeof window === 'undefined') return
    const today = new Date().toISOString().split('T')[0]
    localStorage.setItem(LAST_RUN_KEY, today)
  }

  /**
   * Find all recurring transactions that should fire today
   */
  static async getPendingRecurrences(): Promise<PendingRecurring[]> {
    const allTransactions = await db.transactions.toArray()
    const recurringTxs = allTransactions.filter(tx => tx.isRecurring && tx.recurrenceRule)

    const today = new Date()
    const todayStr = today.toISOString().split('T')[0]
    const pending: PendingRecurring[] = []

    for (const tx of recurringTxs) {
      const txDate = new Date(tx.date + 'T00:00:00')
      let shouldCreate = false

      switch (tx.recurrenceRule) {
        case 'weekly':
          // Same day of week
          shouldCreate = txDate.getDay() === today.getDay()
          break
        case 'monthly':
          // Same day of month
          shouldCreate = txDate.getDate() === today.getDate()
          break
        case 'yearly':
          // Same day + month
          shouldCreate = txDate.getDate() === today.getDate() && txDate.getMonth() === today.getMonth()
          break
      }

      if (shouldCreate) {
        // Check if we already created one today for this recurring source
        const alreadyCreated = allTransactions.some(
          t => t.date === todayStr &&
               t.isAutoGenerated &&
               t.category === tx.category &&
               t.amount === tx.amount &&
               t.description === tx.description
        )

        if (!alreadyCreated) {
          pending.push({ transaction: tx, shouldCreate: true })
        }
      }
    }

    return pending
  }

  /**
   * Auto-create a recurring transaction for today
   */
  static async createRecurringEntry(sourceTx: Transaction): Promise<string> {
    const todayStr = new Date().toISOString().split('T')[0]
    const newId = generateUUID()

    await db.transaction('rw', [db.transactions, db.accounts, db.assets, db.notifications, db.systemLogs], async () => {
      await db.transactions.add({
        id: newId,
        date: todayStr,
        type: sourceTx.type,
        category: sourceTx.category,
        amount: sourceTx.amount,
        accountId: sourceTx.accountId,
        description: sourceTx.description,
        isRecurring: false, // The new entry is not recurring itself
        isAutoGenerated: true,
      })

      // Update account balance
      const account = await db.accounts.get(sourceTx.accountId)
      if (account) {
        const delta = sourceTx.type === 'expense' ? -sourceTx.amount : sourceTx.amount
        const newBalance = account.balance + delta
        await db.accounts.update(sourceTx.accountId, { balance: newBalance })
        await syncAccountToAsset(account.name, newBalance)
      }

      // Create notification
      await db.notifications.add({
        id: generateUUID(),
        type: 'transaction',
        title: 'Recurring Transaction Logged',
        message: `${sourceTx.description} (${sourceTx.type === 'expense' ? '-' : '+'}₹${sourceTx.amount.toLocaleString()}) was auto-logged`,
        read: false,
        timestamp: new Date().toISOString(),
      })

      await db.systemLogs.add({
        id: generateUUID(),
        timestamp: new Date().toISOString(),
        type: 'transaction',
        description: `Auto-logged recurring: ${sourceTx.description} (₹${sourceTx.amount})`,
        amount: sourceTx.type === 'expense' ? -sourceTx.amount : sourceTx.amount,
      })
    })

    return newId
  }

  /**
   * Run the full recurring check — call on app load
   */
  static async processRecurrences(): Promise<number> {
    if (RecurringTransactionService.hasRunToday()) return 0

    const pending = await RecurringTransactionService.getPendingRecurrences()
    let created = 0

    for (const item of pending) {
      await RecurringTransactionService.createRecurringEntry(item.transaction)
      created++
    }

    RecurringTransactionService.markAsRun()
    return created
  }
}
