/**
 * Phase 1.1: Recurring Transactions Auto-Entry
 * Checks on app load if any recurring transactions need to be created today.
 * Uses localStorage to track last-run date and avoid duplicates.
 */

import { db, Transaction, generateUUID, syncAccountToAsset } from '@/db/schema'

const LAST_RUN_KEY = 'pennyflow-recurring-last-run'

export interface PendingRecurring {
  transaction: Transaction
  shouldCreate: boolean
}

export class RecurringTransactionService {
  /**
   * Check if recurring processor has already run today
   */
  static hasRunToday(): boolean {
    if (typeof window === 'undefined') return true
    const lastRun = localStorage.getItem(LAST_RUN_KEY)
    const today = new Date().toISOString().split('T')[0]
    return lastRun === today
  }

  /**
   * Mark today as processed
   */
  static markAsRun(): void {
    if (typeof window === 'undefined') return
    const today = new Date().toISOString().split('T')[0]
    localStorage.setItem(LAST_RUN_KEY, today)
  }

  /**
   * Advance a date by one step of the given cadence.
   */
  private static advance(date: Date, rule: 'weekly' | 'monthly' | 'yearly'): Date {
    const next = new Date(date)
    switch (rule) {
      case 'weekly':
        next.setDate(next.getDate() + 7)
        break
      case 'monthly':
        next.setMonth(next.getMonth() + 1)
        break
      case 'yearly':
        next.setFullYear(next.getFullYear() + 1)
        break
    }
    return next
  }

  /**
   * Enumerate every scheduled occurrence date for a recurring source between
   * the day AFTER its start date and today (inclusive), as YYYY-MM-DD strings.
   * The source's own start date is excluded (that's the original entry).
   *
   * Capped at MAX_OCCURRENCES per source to prevent runaway generation from a
   * long-dormant recurring rule; when capped we keep the MOST RECENT occurrences.
   */
  private static enumerateOccurrences(
    startDateStr: string,
    rule: 'weekly' | 'monthly' | 'yearly'
  ): string[] {
    const MAX_OCCURRENCES = 366 // ~1 year of daily-ish backfill safety cap

    const start = new Date(startDateStr + 'T00:00:00')
    if (isNaN(start.getTime())) return []

    const today = new Date()
    today.setHours(0, 0, 0, 0)

    const dates: string[] = []
    let cursor = this.advance(start, rule)
    let guard = 0

    while (cursor.getTime() <= today.getTime() && guard < 10000) {
      dates.push(cursor.toISOString().split('T')[0])
      cursor = this.advance(cursor, rule)
      guard++
    }

    // If a rule was dormant for a very long time, only backfill the most
    // recent window rather than flooding the ledger with ancient entries.
    if (dates.length > MAX_OCCURRENCES) {
      return dates.slice(dates.length - MAX_OCCURRENCES)
    }
    return dates
  }

  /**
   * Find all missed recurring occurrences that still need to be created,
   * across every scheduled date up to today (this is the backfill).
   * Returns one pending item per (source, missed-date) pair.
   */
  static async getPendingRecurrences(): Promise<PendingRecurring[]> {
    const allTransactions = await db.transactions.toArray()
    const recurringTxs = allTransactions.filter(tx => tx.isRecurring && tx.recurrenceRule)

    // Build a fast lookup of what we've already auto-generated, keyed by a
    // signature of (date + source identity), so re-runs never duplicate.
    const existingKeys = new Set(
      allTransactions
        .filter(t => t.isAutoGenerated)
        .map(t => `${t.date}|${t.category}|${t.amount}|${t.description}|${t.accountId}`)
    )

    const pending: PendingRecurring[] = []

    for (const tx of recurringTxs) {
      if (!tx.recurrenceRule) continue
      const occurrences = this.enumerateOccurrences(tx.date, tx.recurrenceRule)

      for (const occDate of occurrences) {
        const key = `${occDate}|${tx.category}|${tx.amount}|${tx.description}|${tx.accountId}`
        if (existingKeys.has(key)) continue
        // Reserve this key so two recurring sources with identical signature
        // in the same run don't both create for the same date.
        existingKeys.add(key)
        pending.push({ transaction: { ...tx, date: occDate }, shouldCreate: true })
      }
    }

    return pending
  }

  /**
   * Auto-create a recurring transaction entry.
   * Uses `sourceTx.date` as the occurrence date so backfilled entries land on
   * the actual scheduled day, not always today.
   */
  static async createRecurringEntry(sourceTx: Transaction): Promise<string> {
    const occurrenceDate = sourceTx.date || new Date().toISOString().split('T')[0]
    const newId = generateUUID()

    await db.transaction('rw', [db.transactions, db.accounts, db.assets, db.notifications, db.systemLogs], async () => {
      await db.transactions.add({
        id: newId,
        date: occurrenceDate,
        type: sourceTx.type,
        category: sourceTx.category,
        amount: sourceTx.amount,
        accountId: sourceTx.accountId,
        description: sourceTx.description,
        isRecurring: false, // The new entry is not recurring itself
        isAutoGenerated: true,
      })

      // Update account balance
      const account = await db.accounts.get(sourceTx.accountId)
      if (account) {
        const delta = sourceTx.type === 'expense' ? -sourceTx.amount : sourceTx.amount
        const newBalance = account.balance + delta
        await db.accounts.update(sourceTx.accountId, { balance: newBalance })
        await syncAccountToAsset(account.name, newBalance)
      }

      // Notify only for occurrences on today, so a large historical backfill
      // doesn't flood the notification center with dozens of alerts.
      const todayStr = new Date().toISOString().split('T')[0]
      if (occurrenceDate === todayStr) {
        await db.notifications.add({
          id: generateUUID(),
          type: 'transaction',
          title: 'Recurring Transaction Logged',
          message: `${sourceTx.description} (${sourceTx.type === 'expense' ? '-' : '+'}₹${sourceTx.amount.toLocaleString()}) was auto-logged`,
          read: false,
          timestamp: new Date().toISOString(),
        })
      }

      await db.systemLogs.add({
        id: generateUUID(),
        timestamp: new Date().toISOString(),
        type: 'transaction',
        description: `Auto-logged recurring: ${sourceTx.description} (₹${sourceTx.amount})`,
        amount: sourceTx.type === 'expense' ? -sourceTx.amount : sourceTx.amount,
      })
    })

    return newId
  }

  /**
   * Run the full recurring check — call on app load.
   *
   * This now BACKFILLS every missed occurrence up to today, not just entries
   * scheduled for exactly today, so occurrences aren't lost when the app isn't
   * opened on the precise recurrence date. Safe to run repeatedly: occurrences
   * already created are skipped via signature dedup.
   */
  static async processRecurrences(): Promise<number> {
    if (RecurringTransactionService.hasRunToday()) return 0

    const pending = await RecurringTransactionService.getPendingRecurrences()
    const todayStr = new Date().toISOString().split('T')[0]
    let created = 0
    let backfilled = 0

    for (const item of pending) {
      await RecurringTransactionService.createRecurringEntry(item.transaction)
      created++
      if (item.transaction.date !== todayStr) backfilled++
    }

    // If we caught up on missed days, leave a single summary notification.
    if (backfilled > 0) {
      await db.notifications.add({
        id: generateUUID(),
        type: 'transaction',
        title: 'Recurring Transactions Caught Up',
        message: `${backfilled} missed recurring ${backfilled === 1 ? 'entry was' : 'entries were'} added for days the app wasn't opened.`,
        read: false,
        timestamp: new Date().toISOString(),
      })
    }

    RecurringTransactionService.markAsRun()
    return created
  }
}
