import Dexie, { type Table } from 'dexie';

// Define transaction structure
export interface Transaction {
  id: string;
  date: string; // ISO date string (YYYY-MM-DD)
  type: 'income' | 'expense';
  category: string;
  amount: number;
  accountId: string;
  description: string;
  isRecurring: boolean;
  recurrenceRule?: 'weekly' | 'monthly' | 'yearly';
  tags?: string[];
  notes?: string;
  receiptImage?: string; // Phase 1.3: Base64 compressed receipt image
  isAutoGenerated?: boolean; // Phase 1.1: Auto-generated from recurring rule
}

// Define lending structure (loans given to/taken from others)
export interface Lending {
  id: string;
  contactName: string;
  type: 'lent' | 'borrowed';
  amount: number;
  interestRate: number; // annual interest in % (e.g. 5 for 5%)
  interestType: 'none' | 'simple' | 'compound';
  expectedRepaymentDate?: string; // YYYY-MM-DD
  status: 'active' | 'paid';
  createdAt: string; // YYYY-MM-DD
  description?: string;
}

// Define assets structure (cash, bank, stock, gold, crypto, etc.)
export interface Asset {
  id: string;
  name: string;
  type: 'cash' | 'bank' | 'stock' | 'crypto' | 'real_estate' | 'gold';
  balance: number;
  valuationHistory: { date: string; value: number }[]; // Track over time
}

// Define bills structure
export interface Bill {
  id: string;
  title: string;
  amount: number;
  dueDate: string; // YYYY-MM-DD
  category: string;
  isPaid: boolean;
  isRecurring: boolean;
  recurrenceRule?: 'monthly' | 'yearly';
}

// Define goals structure
export interface Goal {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  targetDate: string; // YYYY-MM-DD
  category: string;
  priority?: 'low' | 'medium' | 'high'; // NEW
  milestones?: Array<{ amount: number; date: string; completed: boolean }>; // NEW
  autoSave?: boolean; // NEW: Auto-save toward goal
  autoSaveAmount?: number; // NEW: Monthly auto-save amount
}

// Define accounts structure
export interface Account {
  id: string;
  name: string;
  type: 'cash' | 'bank' | 'card' | 'investment' | 'crypto'; // UPDATED
  balance: number;
  currency?: string; // NEW: Currency code (USD, INR, etc.)
  icon?: string; // NEW: Account icon/emoji
  balanceHistory?: Array<{ date: string; balance: number }>; // NEW: Historical balances
}

// Define system logs structure (chronological timeline)
export interface SystemLog {
  id: string;
  timestamp: string; // ISO timestamp
  type: 'transaction' | 'lending' | 'asset' | 'bill' | 'goal' | 'system';
  description: string;
  amount?: number;
}

// NEW: Budget structure
export interface Budget {
  id: string;
  name: string;
  category: string;
  limit: number;
  period: 'weekly' | 'monthly' | 'yearly'; // NEW
  spent: number;
  startDate: string; // YYYY-MM-DD
  endDate?: string;
  alertThreshold: number; // % of limit before alert (e.g., 80)
  isActive: boolean;
}

// NEW: Custom Category
export interface CustomCategory {
  id: string;
  name: string;
  type: 'income' | 'expense';
  icon?: string;
  color?: string;
  createdAt: string;
}

// NEW: Tag structure
export interface Tag {
  id: string;
  name: string;
  color?: string;
  createdAt: string;
}

// NEW: Investment structure
export interface Investment {
  id: string;
  name: string;
  type: 'stock' | 'crypto' | 'mutual_fund' | 'etf' | 'real_estate' | 'gold';
  symbol?: string; // e.g., AAPL, BTC
  quantity: number;
  buyPrice: number;
  currentPrice: number;
  currentValue: number;
  purchaseDate: string;
  accountId: string;
  notes?: string;
}

// NEW: Notification structure
export interface Notification {
  id: string;
  type: 'bill_due' | 'budget_warning' | 'goal_progress' | 'transaction' | 'system';
  title: string;
  message: string;
  read: boolean;
  timestamp: string;
  actionUrl?: string;
}

// NEW: Financial Brief structure
export interface FinancialBrief {
  id: string;
  period: 'week' | 'month';
  startDate: string;
  endDate: string;
  totalIncome: number;
  totalExpense: number;
  netSavings: number;
  topCategories: Array<{ category: string; amount: number }>;
  insights: string[];
  generatedAt: string;
}

// Phase 0.2: Quick Expense Templates
export interface ExpenseTemplate {
  id: string;
  name: string;
  amount: number;
  category: string;
  accountId: string;
  type: 'expense' | 'income';
  createdAt: string;
  usageCount: number;
}

// Phase 1.2: Split Expenses
export interface SplitExpense {
  id: string;
  transactionId: string; // Links to the original transaction
  totalAmount: number;
  paidBy: string; // Name of who paid
  splitType: 'equal' | 'custom' | 'percentage';
  participants: Array<{
    name: string;
    amount: number;
    settled: boolean;
  }>;
  createdAt: string;
  notes?: string;
}

// Phase 2.10: Subscription Tracker
export interface Subscription {
  id: string;
  name: string;
  amount: number;
  cycle: 'monthly' | 'yearly' | 'weekly';
  category: string;
  nextBilling: string; // YYYY-MM-DD
  startDate: string;
  isActive: boolean;
  notes?: string;
  lastUsed?: string; // Track when last "used" for cancel suggestions
}

// Phase 2.9: Shared Wallets
export interface SharedWallet {
  id: string;
  name: string;
  inviteCode: string;
  members: Array<{
    name: string;
    role: 'owner' | 'editor' | 'viewer';
    balance: number;
  }>;
  transactions: Array<{
    id: string;
    date: string;
    description: string;
    amount: number;
    paidBy: string;
    type: 'expense' | 'income';
  }>;
  createdAt: string;
}

// Debt record for Debt Planner
export interface DebtRecord {
  id: string;
  name: string;
  balance: number;
  interestRate: number;
  minimumPayment: number;
  createdAt: string;
}

// User Profile (stored in DB instead of localStorage for persistence)
export interface UserProfile {
  id: string;
  name: string;
  email: string;
  avatar?: string; // base64 data URL
  currency: string;
  createdAt: string;
  updatedAt: string;
}

class PennyFlowDatabase extends Dexie {
  transactions!: Table<Transaction, string>;
  lending!: Table<Lending, string>;
  assets!: Table<Asset, string>;
  bills!: Table<Bill, string>;
  goals!: Table<Goal, string>;
  accounts!: Table<Account, string>;
  systemLogs!: Table<SystemLog, string>;
  budgets!: Table<Budget, string>;
  customCategories!: Table<CustomCategory, string>;
  tags!: Table<Tag, string>;
  investments!: Table<Investment, string>;
  notifications!: Table<Notification, string>;
  financialBriefs!: Table<FinancialBrief, string>;
  templates!: Table<ExpenseTemplate, string>;
  splits!: Table<SplitExpense, string>;
  subscriptions!: Table<Subscription, string>;
  sharedWallets!: Table<SharedWallet, string>;
  debts!: Table<DebtRecord, string>;
  userProfile!: Table<UserProfile, string>;

  constructor() {
    super('PennyFlowDatabase');

    /**
     * CRITICAL: DATABASE VERSIONING RULES
     * ====================================
     * 1. NEVER delete or modify existing version declarations
     * 2. NEVER change the database name ('PennyFlowDatabase')
     * 3. To add new tables: create a NEW version (increment number)
     *    and include ALL existing tables plus the new one
     * 4. To add new indexes: create a NEW version with the updated index list
     * 5. NEVER remove a table from the stores declaration (it deletes all data in that table)
     * 6. Upgrade functions must be non-destructive (additive only)
     * 7. Test schema changes locally FIRST before deploying
     *
     * Violating these rules WILL cause user data loss in production.
     */

    // Version 6 — preserve existing data (DO NOT remove or modify)
    this.version(6).stores({
      transactions: 'id, date, type, category, accountId',
      lending: 'id, contactName, type, status, createdAt',
      assets: 'id, name, type',
      bills: 'id, title, dueDate, isPaid',
      goals: 'id, title, targetDate',
      accounts: 'id, name, type',
      systemLogs: 'id, timestamp, type',
      budgets: 'id, category, period',
      customCategories: 'id, name, type',
      tags: 'id, name',
      investments: 'id, name, symbol, accountId',
      notifications: 'id, type, timestamp',
      financialBriefs: 'id, period, startDate',
      templates: 'id, name, category, type',
      splits: 'id, transactionId, createdAt',
      subscriptions: 'id, name, cycle, isActive',
      sharedWallets: 'id, name, inviteCode',
      debts: 'id, name, createdAt',
    });

    // Version 7 — add userProfile table (non-destructive upgrade)
    this.version(7).stores({
      transactions: 'id, date, type, category, accountId',
      lending: 'id, contactName, type, status, createdAt',
      assets: 'id, name, type',
      bills: 'id, title, dueDate, isPaid',
      goals: 'id, title, targetDate',
      accounts: 'id, name, type',
      systemLogs: 'id, timestamp, type',
      budgets: 'id, category, period',
      customCategories: 'id, name, type',
      tags: 'id, name',
      investments: 'id, name, symbol, accountId',
      notifications: 'id, type, timestamp',
      financialBriefs: 'id, period, startDate',
      templates: 'id, name, category, type',
      splits: 'id, transactionId, createdAt',
      subscriptions: 'id, name, cycle, isActive',
      sharedWallets: 'id, name, inviteCode',
      debts: 'id, name, createdAt',
      userProfile: 'id',
    }).upgrade(async (tx) => {
      // Migrate profile from localStorage to DB if it exists
      if (typeof window !== 'undefined') {
        const savedProfile = localStorage.getItem('finance-os-profile')
        if (savedProfile) {
          try {
            const profile = JSON.parse(savedProfile)
            await tx.table('userProfile').add({
              id: 'default',
              name: profile.name || '',
              email: profile.email || '',
              avatar: profile.avatar || undefined,
              currency: localStorage.getItem('finance-os-currency') || 'INR',
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            })
          } catch {}
        }
      }
    });
  }
}

export const db = new PennyFlowDatabase();

// Utility for safe UUID generation
export function generateUUID(): string {
  if (typeof window !== 'undefined' && window.crypto && window.crypto.randomUUID) {
    return window.crypto.randomUUID();
  }
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

/**
 * Initialize database on app start.
 * SAFETY: This function NEVER deletes, clears, or overwrites existing data.
 * It only acts on a truly fresh/empty database (brand new install).
 */
export async function seedDatabaseIfEmpty() {
  // Check multiple tables to determine if user has ANY existing data
  const accountCount = await db.accounts.count()
  const transactionCount = await db.transactions.count()
  const goalsCount = await db.goals.count()
  const billsCount = await db.bills.count()

  const hasAnyData = accountCount > 0 || transactionCount > 0 || goalsCount > 0 || billsCount > 0

  if (hasAnyData) {
    // User has existing data — only do non-destructive migrations
    // Migrate profile from localStorage to DB if not already there
    const profileCount = await db.userProfile.count()
    if (profileCount === 0) {
      const savedProfile = localStorage.getItem('finance-os-profile')
      if (savedProfile) {
        try {
          const p = JSON.parse(savedProfile)
          await db.userProfile.add({
            id: 'default',
            name: p.name || '',
            email: p.email || '',
            avatar: p.avatar,
            currency: localStorage.getItem('finance-os-currency') || 'INR',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          })
        } catch {}
      }
    }
    return // Exit — never touch existing data
  }

  // Truly empty database (brand new install / first time user)
  // Just log a welcome entry so the timeline isn't completely empty
  await db.systemLogs.add({
    id: generateUUID(),
    timestamp: new Date().toISOString(),
    type: 'system',
    description: 'Welcome to PennyFlow. Your local database is ready.',
  })
}

// === Profile helpers (stored in DB for persistence) ===

export async function getProfile(): Promise<UserProfile | undefined> {
  return db.userProfile.get('default')
}

export async function saveProfile(data: Partial<UserProfile>): Promise<void> {
  const existing = await db.userProfile.get('default')
  if (existing) {
    await db.userProfile.update('default', { ...data, updatedAt: new Date().toISOString() })
  } else {
    await db.userProfile.add({
      id: 'default',
      name: data.name || '',
      email: data.email || '',
      avatar: data.avatar,
      currency: data.currency || 'INR',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    })
  }
  // Also keep localStorage as backup for quick access
  localStorage.setItem('finance-os-profile', JSON.stringify({
    name: data.name || existing?.name || '',
    email: data.email || existing?.email || '',
    avatar: data.avatar || existing?.avatar,
  }))
  if (data.currency) {
    localStorage.setItem('finance-os-currency', data.currency)
  }
}

// Synchronize Account Balance changes to Assets table
export async function syncAccountToAsset(accountName: string, newBalance: number) {
  const matchingAsset = await db.assets.where('name').equalsIgnoreCase(accountName).first();
  if (matchingAsset) {
    const todayStr = new Date().toISOString().split('T')[0];
    const updatedHistory = [...matchingAsset.valuationHistory];
    const existingIndex = updatedHistory.findIndex(v => v.date === todayStr);
    
    if (existingIndex >= 0) {
      updatedHistory[existingIndex].value = newBalance;
    } else {
      updatedHistory.push({ date: todayStr, value: newBalance });
    }
    
    await db.assets.update(matchingAsset.id, {
      balance: newBalance,
      valuationHistory: updatedHistory
    });
  }
}

// Synchronize Asset Balance changes to Accounts table
export async function syncAssetToAccount(assetName: string, newBalance: number) {
  const matchingAccount = await db.accounts.where('name').equalsIgnoreCase(assetName).first();
  if (matchingAccount) {
    await db.accounts.update(matchingAccount.id, {
      balance: newBalance
    });
  }
}
